title: <p align="center"> Adarsh Singh </p>
logo: /assets/img/profile_photo.jpeg

description: 
[![linkedin](https://img.shields.io/badge/linkedin-0A66C2?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/asceticadarsh/)<br>
[![Mail ID](https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white)](https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox?
compose=GTvVlcSKjRFLBxLDvcPgTVmWBLLPtCmjZsFcZQDdjvjzWtrtJtmcDFGCwPrXkgncThWMHMZmZGgzl)




theme: jekyll-theme-minimal
